POST http://localhost:8050/api/book
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjg4MTU5ODg4LCJleHAiOjE2ODg3NjQ2ODh9.JhKQR3822bBKDuqqsuijyK0Lthk84ogId1Fgth_rLbM

{
    "isbn" : 100,
    "title" : "Don Quijote de la Mancha",
    "author" : "Miguel de Cervantes Saavedra",
    "year" : "1605",
    "libraryId": 1
}





