POST http://localhost:8050/api/library
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjg4MTY3NjQzLCJleHAiOjE2ODg3NzI0NDN9.4U4UiCOHpWT4D0YkTbZKoaU6BS2-tSgzYS0Qfsvst1M

{
    "name" : "Del Norte Libreria",
    "location" : "San Isidro, Catamarca",
    "phone" : "5493834212333"
}

